title: Arsenal
theme: minima
author: Edward Treece
email: edtreece@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site to write about all things Arsenal

# social links
twitter_username: @Treecey_98
github_username:  @Treeceyy

show_excerpts: true # set to false to remove excerpts on the homepage
